export const identities: Record<string, { colours: [string, string][]; headingFont: string; bodyFont: string; direction: string; mark: string }> = {
 'loom-and-kiln': { colours: [['Cream','#FAF7EF'],['Terracotta','#BA592C'],['Ink','#292620'],['White','#FFFFFF']], headingFont: 'Libre Caslon Display', bodyFont: 'Arial', direction: 'A warm editorial identity for an artisan marketplace. A serif wordmark, terracotta details and cream backgrounds echo natural craft materials. Floating photographs connect the identity to the handmade pieces.', mark: 'loom & kiln' },
 'brightpath-academy': { colours: [['White','#FFFFFF'],['Red','#E52D38'],['Black','#070707'],['Soft red','#F08087']], headingFont: 'DM Sans', bodyFont: 'DM Sans', direction: 'A clear, confident tutoring identity adapted from a supplied website template. Bold sans-serif headings, a circular B monogram and vivid red accents frame the learning photography and four lesson formats.', mark: 'BrightPath Academy' },
 'her-circle': { colours: [['Cream','#FFFCF7'],['Wine','#702646'],['Pink','#F4E7E9'],['Green','#244B42']], headingFont: 'Playfair Display', bodyFont: 'DM Sans', direction: 'A warm, welcoming identity for women meeting through shared activities. Wine and soft pink frame the photography, while serif headings and readable supporting text balance personality with clear plans.', mark: 'Her Circle' },
 'sift-and-saffron': { colours: [['Cream','#F7F2EA'],['Cocoa','#432F28'],['Terracotta','#9E4B36'],['Warm grey','#756159']], headingFont: 'Libre Caslon Display', bodyFont: 'DM Sans', direction: 'A warm, personal home bakery identity. A lowercase serif wordmark, an expressive ampersand and cream backgrounds echo the softness of the baking photography.', mark: 'sift & saffron' },
 'noura-beauty-house': { colours: [['Ivory','#FAF7F1'],['Brown','#583B30'],['Clay','#9B6B56'],['Sand','#E8DDCD']], headingFont: 'Cormorant Garamond', bodyFont: 'Manrope', direction: 'A calm beauty identity built around personal care. Fine serif headings, warm browns and generous space give the service menu a soft, considered character.', mark: 'Noura Beauty House' },
 'second-story': { colours: [['Paper','#F8F4EB'],['Burgundy','#642B38'],['Ink','#292B24'],['Yellow','#E8C660']], headingFont: 'Playfair Display', bodyFont: 'DM Sans', direction: 'An editorial identity for secondhand fashion. Burgundy and paper tones frame the photography, with a warm yellow accent for small moments of emphasis.', mark: 'second story' },
 'nisma': { colours: [['Paper','#FAF8F3'],['Forest','#263C30'],['Sage','#E8EDE3'],['Olive','#334B3E']], headingFont: 'Georgia', bodyFont: 'System sans-serif', direction: 'A quiet lifestyle storefront identity. Olive tones and warm paper backgrounds keep the varied catalogue visually consistent.', mark: 'Nisma' },
 'underthehaik': { colours: [['Paper','#F7F3EA'],['Ink','#25231F'],['Olive','#596044'],['Gold','#A47C3C']], headingFont: 'Georgia', bodyFont: 'Arial', direction: 'A book-like publishing identity. A serif masthead, paper backgrounds and restrained olive accents keep the writing at the centre.', mark: 'Under the Haik' },
};
