'use strict';
let products=[], category='All', maker='', query='', sort='featured', currentProduct=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',maximumFractionDigits:0}).format(n);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2200);}
function renderProducts(){let shown=products.filter(p=>(category==='All'||p.category===category)&&(!maker||p.maker===maker)&&(!query||(p.name+' '+p.category+' '+p.maker+' '+p.description).toLowerCase().includes(query.toLowerCase())));if(sort==='low')shown.sort((a,b)=>a.price-b.price);if(sort==='high')shown.sort((a,b)=>b.price-a.price);$('#results').textContent=shown.length+' pieces'+(maker?' from '+maker:'')+(query?' matching “'+query+'”':'');$('#products').innerHTML=shown.length?shown.map(p=>'<article class="product-card"><button class="product-image" data-view="'+p.id+'" aria-label="View '+esc(p.name)+'"><img src="'+p.image+'" alt="'+esc(p.name)+'" width="800" height="900" loading="lazy"></button><div><p class="meta">'+esc(p.maker)+'</p><h3><button class="product-name" data-view="'+p.id+'">'+esc(p.name)+'</button></h3><div class="product-bottom"><p class="price">'+money(p.price)+'</p><button class="view-button" data-view="'+p.id+'">View piece</button></div></div></article>').join(''):'<div class="empty"><h3>No pieces found.</h3><p>Try a different word or explore the complete collection.</p><button class="button outline" id="reset">Show all pieces</button></div>';document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));return shown;}
function filterCollection(options={}){category=options.category||'All';maker=options.maker||'';query=options.query||'';$('#search').value=query;const shown=renderProducts();$('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return shown;}
function openProduct(id){const p=products.find(p=>p.id===Number(id));if(!p)throw Error('Unknown piece');currentProduct=p;$('#product-detail').innerHTML='<img src="'+p.image+'" alt="'+esc(p.name)+'" width="800" height="900"><div><p class="eyebrow">'+esc(p.category)+'</p><h2 id="product-title">'+esc(p.name)+'</h2><p class="detail-maker">An imagined collection by '+esc(p.maker)+'</p><p class="detail-description">'+esc(p.description)+'</p><p class="detail-price">'+money(p.price)+'</p><p class="pill">Discover artisan finds at the Saturday market</p><p class="detail-note">Sample piece and price. Exact materials and dimensions are not specified.</p></div>';$('#product-dialog').showModal();}
document.addEventListener('click',e=>{if(e.target.closest('[data-reset-collection]')){e.preventDefault();filterCollection();}const view=e.target.closest('[data-view]');if(view)openProduct(view.dataset.view);const cat=e.target.closest('[data-category]');if(cat)filterCollection({category:cat.dataset.category});const studio=e.target.closest('[data-maker]');if(studio)filterCollection({maker:studio.dataset.maker});const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close();if(e.target.id==='reset')filterCollection();});
$('#search-form').addEventListener('submit',e=>{e.preventDefault();filterCollection({query:$('#search').value.trim()});});$('#sort').addEventListener('change',e=>{sort=e.target.value;renderProducts();});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
fetch('catalogue.json').then(r=>{if(!r.ok)throw Error('Catalogue unavailable');return r.json();}).then(data=>{products=data;renderProducts();registerTools();}).catch(()=>{$('#results').textContent='The collection could not load. Please refresh the page.';});
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tools=[{name:'search_craft_collection',title:'Search craft collection',description:'Filter the visible collection by search text or category.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:['All','Ceramics','Jewellery','Embroidery','Woven bags','Soaps']}},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||(input.query!==undefined&&typeof input.query!=='string')||(input.category&&!['All','Ceramics','Jewellery','Embroidery','Woven bags','Soaps'].includes(input.category)))throw Error('Invalid search');return filterCollection(input).map(({id,name,price,category})=>({id,name,price,category}));}}];tools.forEach(tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}});}
